---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntu1804
    image: ubuntu:18.04
  - name: ubuntu2004
    image: ubuntu:20.04
provisioner:
  name: ansible
scenario:
  name: old_repo
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
