---
stages:
  - build
  - molecule

# See https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
variables:
  DOCKER_REPOSITORY: $CI_REGISTRY_IMAGE/buildx
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

Build Docker image:
  stage: build
  only:
    changes:
      - .dockerfile-ci
      - .gitlab-ci.yml
  interruptible: true
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker -D login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker -D build -f .dockerfile-ci -t $DOCKER_REPOSITORY .
    - docker -D push $DOCKER_REPOSITORY

Run linter:
  stage: molecule
  image: $CI_REGISTRY_IMAGE/buildx
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 python3-dev py3-pip py3-lxml
      build-base rust cargo libffi libffi-dev openssl openssl-dev libxml2
      libxml2-dev linux-headers libxslt libxslt-dev
    - pip3 install pip setuptools --upgrade
    - docker info
  script:
    - docker -v
    - docker buildx install
    - python3 -V
    - pip3 install -r molecule/requirements.txt
    - ansible --version
    - ansible-lint defaults/ tasks/
    - yamllint defaults/ tasks/
  tags:
    - docker

Run molecule:
  stage: molecule
  image: $CI_REGISTRY_IMAGE/buildx
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 python3-dev py3-pip py3-lxml
      build-base rust cargo libffi libffi-dev openssl openssl-dev libxml2
      libxml2-dev linux-headers libxslt libxslt-dev
    - pip3 install pip setuptools --upgrade
    - docker info
  script:
    - docker -v
    - docker buildx install
    - python3 -V
    - pip3 install -r molecule/requirements.txt
    - ansible --version
    - molecule --version
    - molecule test --all
  tags:
    - docker
