---
image: docker:stable

stages:
  - molecule

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache python python-dev py-pip build-base
    libffi libffi-dev openssl openssl-dev linux-headers
  - pip install pip setuptools --upgrade
  - pip install ansible molecule docker
  - docker info
  - source /virtenv/bin/activate

molecule:
  stage: molecule
  script:
    - docker -v
    - python -V
    - pip install -r requirements.txt
    - ansible --version
    - molecule --version
    - molecule test
