---
test:ubuntu1606:
  image: geerlingguy/docker-ubuntu1604-ansible

  script:
    - ansible-playbook -i tests/inventory tests/test.yml -vvv --extra-vars "ci_role_path=../ansible-crystal"

test:ubuntu1804:
  image: geerlingguy/docker-ubuntu1804-ansible

  script:
    - ansible-playbook -i tests/inventory tests/test.yml -vvv --extra-vars "ci_role_path=../ansible-crystal"

test:centos:
  image: geerlingguy/docker-centos7-ansible

  script:
    - ansible-playbook -i tests/inventory tests/test.yml -vvv --extra-vars "ci_role_path=../ansible-crystal"
