---
- name: Debian common block
  when: ansible_os_family == "Debian"
  block:
    - name: Install commom crystal build dependencies
      ansible.builtin.apt:
        name:
          - build-essential
          - libssl-dev

- name: RedHat common block
  when: ansible_os_family == "RedHat"
  block:
    - name: Install common crystal build dependencies
      ansible.builtin.yum:
        name:
          - "@Development tools"
          - openssl-devel
