---
- block:
    - name: Install commom crystal build dependencies
      apt:
        name:
          - build-essential
          - libssl-dev

  when: ansible_os_family == "Debian"

- block:
    - name: Install common crystal build dependencies
      yum:
        name:
          - "@Development tools"
          - openssl-devel

  when: ansible_os_family == "RedHat"
