---
- name: Deprecation warning
  ansible.builtin.fail:
    msg: "'crystal_install_method: package' value is deprecated, use 'repository' or 'standalone' instead."
  failed_when: crystal_install_method is not defined
  when: crystal_install_method == "package"

- include_tasks: repository.yml
  when: crystal_install_method == "package" or crystal_install_method == "repository"

- include_tasks: standalone.yml
  when: crystal_install_method == "standalone"

- include_tasks: build.yml
  when: crystal_build_deps
