---
- name: Deprecation warning
  fail:
    msg: "'crystal_install_method: package' value is deprecated, use 'repository' or 'standalone' instead."
  ignore_errors: true
  when: crystal_install_method == "package"

- include: repository.yml
  when: crystal_install_method == "package" or crystal_install_method == "repository"

- include: standalone.yml
  when: crystal_install_method == "standalone"

- include: build.yml
  when: crystal_build_deps
