---
- block:
    - name: Ensure cache is updated for testing
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_virtualization_type == "docker"

    - name: Install additional dependancies
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https

    - name: Add the crystal apt signing key
      apt_key:
        id: 09617FD37CC06B54
        data: "{{ item }}"
      with_file: crystal-apt.gpg.pub

    - name: Add crystal apt repository
      apt_repository:
        repo: "deb https://dist.crystal-lang.org/apt crystal main"
        state: present

    - name: Install crystal
      apt:
        name: crystal
        update_cache: yes
        state: "{{ crystal_state }}"

  when: ansible_os_family == "Debian"

- block:
    - name: Copy key to remote host
      copy:
        src: crystal-apt.gpg.pub
        dest: /usr/local/src/crystal-apt.gpg.pub

    - name: Add the crystal rpm signing key
      rpm_key:
        state: present
        key: /usr/local/src/crystal-apt.gpg.pub

    - name: Add crystal rpm repository
      yum_repository:
        name: Crystal
        description: Crystal rpm repository
        file: crystal.repo
        state: present
        baseurl: http://dist.crystal-lang.org/rpm/

    - name: Install crystal
      yum:
        name: crystal
        update_cache: yes
        state: "{{ crystal_state }}"
  when: ansible_os_family == "RedHat"
