---
- name: Ensure ansible module dependancies are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - unzip

- name: Download crystal binary
  ansible.builtin.get_url:
    url: "https://github.com/crystal-lang/crystal/releases/download/{{ crystal_version }}/{{ crystal_release }}.tar.gz"
    dest: "/usr/local/src/{{ crystal_release }}.tar.gz"
    mode: "0755"
    checksum: "{{ crystal_checksum }}"

- name: Ensure destination folder exists
  ansible.builtin.file:
    path: "/usr/local/src/{{ crystal_release }}"
    state: directory
    mode: "0755"

- name: Unarchive crystal binary
  ansible.builtin.unarchive:
    src: "/usr/local/src/{{ crystal_release }}.tar.gz"
    dest: "/usr/local/src/{{ crystal_release }}"
    extra_opts: "--strip-components=1"
    remote_src: true

- name: Symlink crystal binary with version
  ansible.builtin.file:
    src: "/usr/local/src/{{ crystal_release }}/bin/crystal"
    dest: "/usr/local/bin/crystal-{{ crystal_version }}"
    mode: "0755"
    force: true
    state: link

- name: Symlink crystal standalone bin without version
  ansible.builtin.file:
    src: "/usr/local/src/{{ crystal_release }}/bin/crystal"
    dest: "/usr/local/bin/crystal"
    mode: "0755"
    state: link
    force: true
