---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: stream8
    image: ${CENTOS_STREAM_EIGHT_IMAGE:-quay.io/centos/centos:stream8}
    pre_build_image: true
  - name: ubuntu2204
    image: ${UBUNTU_JAMMY_IMAGE:-ubuntu:22.04}
    pre_build_image: true
  - name: ubuntu2404
    image: ${UBUNTU_NOBLE_IMAGE:-ubuntu:24.04}
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
