---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: ${CENTOS_EIGHT_IMAGE:-centos:centos8}
  - name: centos7
    image: ${CENTOS_SEVEN_IMAGE:-centos:centos7}
  - name: ubuntu1804
    image: ${UBUNTU_BIONIC_IMAGE:-ubuntu:18.04}
  - name: ubuntu2004
    image: ${UBUNTU_FOCAL_IMAGE:-ubuntu:20.04}
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
