---
- name: Converge
  hosts: all
  roles:
    - role: ansible-crystal
      crystal_install_method: package
      crystal_build_deps: true

    - role: ansible-crystal
      crystal_install_method: standalone
      crystal_revision: 1
      crystal_version: 0.27.2
      crystal_build_deps: true
